namespace :redis do
  desc "Run Redis service"
  task :run do
    process_erb("#{ENV['APP_APP_DIR']}/srv/redis/config/config.conf.erb", "#{ENV['APP_APP_DIR']}/srv/redis/config/config.conf")

    sh "#{ENV['APP_VENDOR_DIR']}/redis/src/redis-server #{ENV['APP_APP_DIR']}/srv/redis/config/config.conf"
  end
end
