require 'yaml'

namespace :package do
namespace :shippers do
namespace :windows do  

  desc "Package a windows shipper"
  task :shipper, :shipper_config_folder, :package_destination_folder, :version do |t, args|
    ENV['version']=args[:version]||"v0.0"
    settings = YAML::load_file(File.join args[:shipper_config_folder], "settings.yml")
    ENV['name'] = settings['name']||"windows-shipper"
    ENV['shipper_config_folder'] = args[:shipper_config_folder]

    puts "Packaging #{args[:shipper_config_folder]} #{ENV['version']} to #{args[:package_destination_folder]}"
    puts "settings: #{settings.inspect}"

    dest="#{ENV['APP_APP_DIR']}/#{args[:package_destination_folder]}"
    FileUtils.mkdir_p dest

    puts "------> Fetching executables"
    sh "DEST='#{dest}' #{ENV['APP_APP_DIR']}/srv/shippers/windows/shipper/provision.sh"
    
    puts "------> Writing config files"
    process_erb("#{ENV['APP_APP_DIR']}/srv/shippers/windows/shipper/config/config.conf.erb", "#{dest}/config.conf")
    process_erb("#{ENV['APP_APP_DIR']}/srv/shippers/windows/shipper/config/windows-shipper-service.exe.config.erb", "#{dest}/windows-shipper-service.exe.config")
    process_erb("#{ENV['APP_APP_DIR']}/srv/shippers/windows/shipper/config/windows-shipper-service.xml.erb", "#{dest}/windows-shipper-service.xml")

    puts "------> Creating Setup.cmd"
    process_erb("#{ENV['APP_APP_DIR']}/srv/shippers/windows/shipper/config/Setup.cmd.erb", "#{dest}/Setup.cmd")

    puts "------> Done!"
    puts "Copy #{args[:package_destination_folder]} to a Windows machine and run Setup.cmd"
  end

end
end
end